### ISSUE TITLE
When finishing byte, if you earn EXP but not level up, confirm does nothing.

### ISSUE THREAD

**Issue by keremimo** [Gage-Technologies/gigo.dev#4]
Hello, there are no guidelines yet and this is my first issue report so please bear with me.

Browser: Firefox
OS: Arch Linux

Issue: When I finish a byte in a journey (For me it was Javascript) a component pops up showing me how much EXP I earned. If it doesn't result in a level up that in turn gives me a loop box, the confirm button is unresponsive and I have to refresh the page to regain functionality.

Reproduction steps: Finish a byte, earn EXP not enough to level up.

Thank you for your work!

**Comment by sam-ulrich1** [comment]
Hey man! Thanks for the bug report!
I'll have someone on the team take a look today. We'll keep you updated

**Comment by sam-ulrich1** [comment]
@Keremimo Is there any chance you have a touch screen? Off the top of my head I think it may be an AwesomeButton there and those don't work on touch screen. We though we had replaced all the instances of those but we might've missed it!

**Comment by keremimo** [comment]
> @Keremimo Is there any chance you have a touch screen? Off the top of my head I think it may be an AwesomeButton there and those don't work on touch screen. We though we had replaced all the instances of those but we might've missed it!

It is the big green confirm button, and no, it isn't a touch screen. I'm using a regular desktop PC :)

**Comment by sam-ulrich1** [comment]
No worries! I'm sure we'll find it. Thanks for the info

**Comment by sam-ulrich1** [comment]
@Keremimo I checked it out myself. I wasn't able to directly reproduce it but I think I know why it happens. I rolled out an update that should probably fix it. Just refresh the page before continuing. Sorry for the inconvenience!

**Comment by keremimo** [comment]
I just tested it by leveling up and it did not repeat. Will re-open issue if it happens again, otherwise thank you for the quick fix!

**Comment by sam-ulrich1** [comment]
No problem! Thanks for the bug report!
